### PR TITLE
Fixes to samples and some improvements

### LINKED ISSUE #839: List sample initial display density not matching radio button
Open https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/list#web-components-list-example

Observe the list display density and the checked radio being "large", which doesn't corresponds to the list initial display density.

### PR DESCRIPTION
**Pull request by skrustev**
Closes #839
Related to https://github.com/IgniteUI/igniteui-xplat-examples/issues/705

### CODE REVIEW

File: samples/grids/grid/clipboard-operations/src/index.ts [hunk 1]
```diff
@@ -42,9 +43,10 @@ export class Sample {
                 grid.cellSelection = 'multiple';
             });
 
+            this.defaultSeparator = grid.clipboardOptions.separator;
```
Comment (IMinchev64) [inline samples/grids/grid/clipboard-operations/src/index.ts:46]: Sample throws error:
image

Additionally, the igcChange event seems to not trigger for some reason, so the default separator is used regardless of what is in entered into the input.

Same issue applies to the tree grid clipboard operations sample

**Review by IMinchev64 — CHANGES_REQUESTED** [review]

File: samples/grids/grid/clipboard-operations/src/index.ts (hunk 1 above)
Comment (skrustev) [reply samples/grids/grid/clipboard-operations/src/index.ts]: Should be ok now

**Review by IMinchev64 — APPROVED** [review]
