### PR TITLE
feat(dock-manager): add split pane fixed size sample

### LINKED ISSUE #877: Create a sample demonstrating DockManager's `useFixedSize` property

### PR DESCRIPTION
**Pull request by igdmdimitrov**
Closes #877

### CODE REVIEW

File: samples/layouts/dock-manager/split-pane-fixed-size/src/index.ts [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+    private dockManager: IgcDockManagerComponent;
+
+    constructor() {
+        this.dockManager = document.getElementById('dockManager') as IgcDockManagerComponent;
+        this.dockManager.dir = 'ltr';
+
+        this.dockManager.layout = {
+            rootPane: {
+                type: IgcDockManagerPaneType.splitPane,
+                orientation: IgcSplitPaneOrientation.vertical,
```
Comment (gedinakova) [inline samples/layouts/dock-manager/split-pane-fixed-size/src/index.ts:21]: How about we make the root useFixedSize: true as well?
```suggestion
                orientation: IgcSplitPaneOrientation.vertical,
                useFixedSize: true,
```

**Review by gedinakova — CHANGES_REQUESTED** [review]

**Review by gedinakova — DISMISSED** [review]

File: samples/layouts/dock-manager/add-content-runtime/package.json [hunk 2]
```diff
@@ -23,7 +23,7 @@
     "@webcomponents/template": "^1.4.2",
     "babel-runtime": "^6.26.0",
     "core-js": "^3.6.5",
-    "igniteui-dockmanager": "1.15.2",
+    "igniteui-dockmanager": "1.16.0-beta.7",
```
Comment (gedinakova) [inline samples/layouts/dock-manager/add-content-runtime/package.json:26]:
```suggestion
    "igniteui-dockmanager": "1.16.0",
```

File: samples/layouts/dock-manager/contained-in-boundaries/package.json [hunk 3]
```diff
@@ -23,7 +23,7 @@
     "@webcomponents/template": "^1.4.2",
     "babel-runtime": "^6.26.0",
     "core-js": "^3.6.5",
-    "igniteui-dockmanager": "1.15.2",
+    "igniteui-dockmanager": "1.16.0-beta.7",
```
Comment (gedinakova) [inline samples/layouts/dock-manager/contained-in-boundaries/package.json:26]:
```suggestion
    "igniteui-dockmanager": "1.16.0",
```

File: samples/layouts/dock-manager/customize-buttons/package.json [hunk 4]
```diff
@@ -23,7 +23,7 @@
     "@webcomponents/template": "^1.4.2",
     "babel-runtime": "^6.26.0",
     "core-js": "^3.6.5",
-    "igniteui-dockmanager": "1.15.2",
+    "igniteui-dockmanager": "1.16.0-beta.7",
```
Comment (gedinakova) [inline samples/layouts/dock-manager/customize-buttons/package.json:26]:
```suggestion
    "igniteui-dockmanager": "1.16.0",
```

File: samples/layouts/dock-manager/focus-panes/package.json [hunk 5]
```diff
@@ -23,7 +23,7 @@
     "@webcomponents/template": "^1.4.2",
     "babel-runtime": "^6.26.0",
     "core-js": "^3.6.5",
-    "igniteui-dockmanager": "1.15.2",
+    "igniteui-dockmanager": "1.16.0-beta.7",
```
Comment (gedinakova) [inline samples/layouts/dock-manager/focus-panes/package.json:26]:
```suggestion
    "igniteui-dockmanager": "1.16.0",
```

File: samples/layouts/dock-manager/proximity-dock/package.json [hunk 6]
```diff
@@ -23,7 +23,7 @@
     "@webcomponents/template": "^1.4.2",
     "babel-runtime": "^6.26.0",
     "core-js": "^3.6.5",
-    "igniteui-dockmanager": "1.15.2",
+    "igniteui-dockmanager": "1.16.0-beta.7",
```
Comment (gedinakova) [inline samples/layouts/dock-manager/proximity-dock/package.json:26]:
```suggestion
    "igniteui-dockmanager": "1.16.0",
```

File: samples/layouts/dock-manager/split-pane-fixed-size/package.json [hunk 7]
```diff
@@ -0,0 +1,58 @@
...
+    "serve:prod:legacy": "webpack-dev-server --env.NODE_ENV=production --env.legacy=true --mode production --config ./webpack.config.js --port 3000 --host 0.0.0.0 --hot --progress --open --content-base dist/",
+    "start:legacy": "npm run serve:dev:legacy"
+  },
+  "author": "Infragistics",
+  "dependencies": {
+    "@webcomponents/custom-elements": "^1.4.1",
+    "@webcomponents/template": "^1.4.2",
+    "babel-runtime": "^6.26.0",
+    "core-js": "^3.6.5",
+    "igniteui-dockmanager": "1.16.0-beta.7",
```
Comment (gedinakova) [inline samples/layouts/dock-manager/split-pane-fixed-size/package.json:26]:
```suggestion
    "igniteui-dockmanager": "1.16.0",
```

File: samples/layouts/dock-manager/toggle-inner-dock/package.json [hunk 8]
```diff
@@ -23,7 +23,7 @@
     "@webcomponents/template": "^1.4.2",
     "babel-runtime": "^6.26.0",
     "core-js": "^3.6.5",
-    "igniteui-dockmanager": "1.15.2",
+    "igniteui-dockmanager": "1.16.0-beta.7",
```
Comment (gedinakova) [inline samples/layouts/dock-manager/toggle-inner-dock/package.json:26]:
```suggestion
    "igniteui-dockmanager": "1.16.0",
```

File: samples/layouts/dock-manager/hide-pane-headers/package.json [hunk 9]
```diff
@@ -23,7 +23,7 @@
     "@webcomponents/template": "^1.4.2",
     "babel-runtime": "^6.26.0",
     "core-js": "^3.6.5",
-    "igniteui-dockmanager": "1.15.2",
+    "igniteui-dockmanager": "1.16.0-beta.7",
```
Comment (gedinakova) [inline samples/layouts/dock-manager/hide-pane-headers/package.json:26]:
```suggestion
    "igniteui-dockmanager": "1.16.0",
```

**Review by gedinakova — APPROVED** [review]
